# This is a basic workflow to help you get started with Actions

name: Lab 6 - Main Lab

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'lab6.*'
      
  pull_request:
    branches: [ main ]
    paths:
      - 'lab6.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          path: ./assignment

      - name: Checkout Tester
        uses: actions/checkout@v4
        with:
          repository: seneca-ipc144/testers
          token: ${{ secrets.TESTER_ACCESS }}
          path: ./tester

      - name: Copy cpp tester files
        run: cp ./tester/lab6tester.c ./

      - name: Copy assignment files
        run:  cp ./assignment/lab6.* ./


      # Runs a single command using the runners shell
      - name: Compile
        run: gcc lab6.c lab6tester.c -o lab6

      # Runs a set of commands using the runners shell
      - name: Run
        run: ./lab6

