name: Project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'project*'
      
  pull_request:
    branches: [ main ]
    paths:
      - 'project*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          path: ./assignment

      - name: Checkout Tester
        uses: actions/checkout@v4
        with:
          repository: seneca-ipc144/testers
          token: ${{ secrets.TESTER_ACCESS }}
          path: ./tester

      - name: Copy test runners
        run: cp ./tester/*.py ./
      
      - name: Copy test runners
        run: cp ./tester/*.csv ./

      - name: Copy assignment files
        run:  |
          cp ./assignment/project.c ./
          cp ./assignment/project.h ./
          cp ./assignment/projectmain.c ./



      - name: Compile C programs
        run: |
          gcc project.c projectmain.c -o project


      - name: Run Project - EXPAND TO SEE RESULTS
        run: |
          echo "Running your program."
          echo
          timeout 60 python ./project2test1.py
          echo
          echo "Checking your combined.txt file"
          echo
          python ./project2test2.py
